[package]
name = "helper"
version = "0.1.0"
authors = ["Tom <tom@ciphersink.net>"]
edition = "2021"
rust-version = "1.71"


[dependencies]
egui.workspace = true
egui_extras.workspace = true
egui-toast.workspace = true