[package]
name = "eq"
version = "0.1.0"
authors = ["Tom <tom@ciphersink.net>"]
edition = "2021"
rust-version = "1.71"


[dependencies]
heapless.workspace = true
num.workspace = true
fast-math.workspace = true

chumsky.workspace = true
nalgebra.workspace = true
