[package]
name = "detailer"
version = "0.1.0"
authors = ["Tom <tom@ciphersink.net>"]
edition = "2021"
rust-version = "1.71"


[dependencies]
drawing.workspace = true

egui.workspace = true
egui_extras.workspace = true
egui-toast.workspace = true
slotmap.workspace = true
serde.workspace = true